apiVersion: sample.codearts.crossplane.io/v1alpha1
kind: MyType
metadata:
  name: helm-example-resource-1
spec:
  forProvider:
    message: dsasffffffffffffffffafffffffffffffdasfdsa
    status: Progressing
    oldStatus: Healthy 
    # patterned: "?"