apiVersion: deploy.codearts.crossplane.io/v1alpha1
kind: Host
metadata:
  name: example-host-proxy
spec:
  forProvider:
    region: cn-north-7
    projectIdRef:
      name: example-project
    clusterIdRef:
      name: example-infrastructurecluster-type-host
    hostName: example-host-proxy
    ip: 1.2.3.4
    osType: linux
    port: 22
    authType: password
    userName: "root"
    authInfoSecretRef:
      name: auth-info-secret
      key: password
      namespace: default
    asProxy: true
---
apiVersion: deploy.codearts.crossplane.io/v1alpha1
kind: Host
metadata:
  name: example-host-target
spec:
  forProvider:
    region: cn-north-7
    projectIdRef:
      name: example-project
    clusterIdRef:
      name: example-infrastructurecluster-type-host
    hostName: example-host-target
    ip: 5.6.7.8
    osType: linux
    port: 22
    authType: private_key
    userName: "root"
    authInfoSecretRef:
      name: auth-info-secret
      key: private_key
      namespace: default
    asProxy: false
    proxyHostIdRef:
      name: example-host-proxy
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-info-secret
type: Opaque
stringData:
  password: "super-secret-placeholder-123"
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEA75P77zJv8v6q6h7z8p9a0b1c2d3e4f5g6h7i8j9k0l1m2n3o
    p4q5r6s7t8u9v0w1x2y3z4a5b6c7d8e9f0g1h2i3j4k5l6m7n8o9p0q1r2s3t4u
    v5w6x7y8z9a0b1c2d3e4f5g6h7i8j9k0l1m2n3o4p5q6r7s8t9u0v1w2x3y4z5a
    6b7c8d9e0f1g2h3i4j5k6l7m8n9o0p1q2r3s4t5u6v7w8x9y0z1a2b3c4d5e6f7
    g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z7a8b9c0d1e2f3g4h5i6j7k8l
    9m0n1o2p3q4r5s6t7u8v9w0x1y2z3a4b5c6d7e8f9g0h1i2j3k4l5m6n7o8p9q0
    -----END RSA PRIVATE KEY-----